# Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# import the dataset

In [4]:
dataset = pd.read_csv(r'F:\Projects\Data.csv')
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

# Taking Care of missing Data

In [5]:
dataset.isnull().any()

Country      False
Age           True
Salary        True
Purchased    False
dtype: bool

# Label Encoding

In [8]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
dataset['Country'] = labelencoder_y.fit_transform(dataset['Country'])

# Splitting Dataset in to Independent variable and Dependent variable

In [9]:
x = dataset.iloc[:, 0:3].values
y = dataset.iloc[:, 3].values

# One Hot Encoding

In [46]:
dataset = pd.read_csv(r'F:\Projects\Data.csv')
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [48]:
dataset.tail()

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [49]:
dataset.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [51]:
dataset["Country"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [55]:
dataset["Purchased"].unique()

array(['No', 'Yes'], dtype=object)

In [56]:
ohe = OneHotEncoder()

In [57]:
print (ohe)

OneHotEncoder()


In [61]:
ohe.fit_transform(dataset[["Country", "Purchased"]]).toarray()

array([[1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.]])

# Splitting The dataset in to Train set and Testing set

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
x_train,x_test,y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [65]:
x_train

array([[4.00000000e+01, 6.37777778e+04],
       [3.70000000e+01, 6.70000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.40000000e+01, 7.20000000e+04],
       [3.50000000e+01, 5.80000000e+04]])

In [66]:
x_test

array([[3.0e+01, 5.4e+04],
       [5.0e+01, 8.3e+04]])

# Normalizing

In [81]:
from sklearn.preprocessing import StandardScaler

In [83]:
standard=StandardScaler()
x_train=standard.fit_transform(x_train)

In [84]:
x_test=standard.fit_transform(x_test)

In [85]:
x_train

array([[ 0.26306757,  0.12381479],
       [-0.25350148,  0.46175632],
       [-1.97539832, -1.53093341],
       [ 0.05261351, -1.11141978],
       [ 1.64058505,  1.7202972 ],
       [-0.0813118 , -0.16751412],
       [ 0.95182631,  0.98614835],
       [-0.59788085, -0.48214934]])

In [86]:
x_test

array([[-1., -1.],
       [ 1.,  1.]])